add lesson_09.1
PavlovVitalii/Front-End-Pro pull request #10
Opened 2022-10-27 13:52 UTC by PavlovVitalii

2022-10-31 18:25 UTC, vb-oiko requested changes
Що потрібно зробити

1. Створити клас Людина
    властивості 
        імʼя
        стать
    методи
        конструктор, який приймає два параметри: імʼя та стать
2. клас Квартира
    властивості 
        конструктор не потрібен
        масив жителів, який при створенні пустий
    методи 
        додати жителя - метод повинен приймати екземпляр класу Людина, та додавати до масиву жителів
3. клас Будинок 
    властивості 
        масив квартир, який при створенні пустий
        максимальна кількість квартир
    методи
        конструктор, який приймає один параметр: максимальну кількість квартир
        додати квартиру - метод повинен приймати екземпляр класу Квартира, перевіряти, чи не буде кількість перевищувати максимальну кількість квартир, і якщо це так, додати квартиру, в іншому випадку виводить у консоль відповідне повідомлення

в якості демонстраціїї створити:
    декілька екземплярів класу Людина
    декілька екземплярів класу Квартира
    додадити екземпляри класу Людина до екземплярів класу Квартира
    екземпляр класу Будинок
    додадити екземпляри класу Квартира до екземплярів класу Будинок

2022-11-01 16:43 UTC, PavlovVitalii commented
Задача з авто не коректно виводить данні я не розумію чому.

2022-11-01 19:41 UTC, PavlovVitalii commented
Все виправив. Дякую за лекцію!

2022-11-01 19:45 UTC, PavlovVitalii commented
Щось не те пушиться.

2022-11-01 19:53 UTC, PavlovVitalii commented
Вибачте все добре.  Коректний передостанній коміт.

2022-11-02 16:49 UTC, vb-oiko commented on lesson_09/lesson_09.1/models/Human.js
> +  createInfo() {
```suggestion
  getInfo() {
```

2022-11-02 16:49 UTC, vb-oiko commented on lesson_09/lesson_09.2/models/Car.js
> +  showInfoCar() {
```suggestion
  showInfo() {
```

2022-11-02 16:50 UTC, vb-oiko approved these changes

2022-11-02 19:36 UTC, PavlovVitalii commented on lesson_09/lesson_09.1/models/Human.js
> +  createInfo() {
Виправив.

2022-11-02 19:36 UTC, PavlovVitalii commented on lesson_09/lesson_09.2/models/Car.js
> +  showInfoCar() {
Виправив.

2022-11-03 16:34 UTC, merged