add lesson_11 tasck_26
PavlovVitalii/Front-End-Pro pull request #16
Opened 2022-11-17 15:38 UTC by PavlovVitalii

2022-11-17 17:08 UTC, vb-oiko commented on lesson_11/task_26/tasck_26.js
> +}
Ваш код працює без помилок лише на тих даних, які надвно у завданні.
Але якщо довжина `list` буде більшою довжини `productsList` буде помилка
це потрібно виправити

2022-11-17 17:09 UTC, vb-oiko requested changes
Треба зробити так, щок код працював з будь якими даними

2022-11-17 18:44 UTC, PavlovVitalii commented on lesson_11/task_26/tasck_26.js
> +}
Виправив.

2022-11-18 08:16 UTC, vb-oiko commented on lesson_11/task_26/tasck_26.js
> +      productsUl.appendChild(li);
Тут Ви у циклі додаєте той самий елемент декілька разів, це не вирішує проблему
А потрібно створити декілька елементів

2022-11-18 10:14 UTC, PavlovVitalii commented on lesson_11/task_26/tasck_26.js
> +      productsUl.appendChild(li);
Виправив.

2022-11-19 13:56 UTC, vb-oiko approved these changes

2022-11-22 07:18 UTC, merged