add task_37
PavlovVitalii/Front-End-Pro pull request #25
Opened 2023-01-26 09:24 UTC by PavlovVitalii

2023-01-26 15:53 UTC, vb-oiko commented on lesson_31_task_37/src/App.js
> +      setItems([...items, { title: value, isDone: false }]);
```suggestion
      setItems([...items, { title: value.trim(), isDone: false }]);
```

2023-01-26 15:56 UTC, vb-oiko commented on lesson_31_task_37/src/App.js
> +  };
якщо в масиві буде декілька елементів з однаковим `title`, логіка перемикання стану одноіменних тудушок буде працювати не вірно

2023-01-26 15:57 UTC, vb-oiko commented on lesson_31_task_37/src/App.js
> +            key={index}
використовівати індекс масива у якості `key` не є гарною практикою

2023-01-26 16:00 UTC, vb-oiko requested changes
Треба додати уникальний айді до обєкта тудушки, щоб коректно працювала логіка зміни стану

2023-01-27 08:49 UTC, PavlovVitalii commented on lesson_31_task_37/src/App.js
> +            key={index}
Виправив.

2023-01-27 15:02 UTC, vb-oiko approved these changes

2023-01-27 20:23 UTC, merged