Feature/lesson 05
PavlovVitalii/Front-End-Pro pull request #5
Opened 2022-10-14 18:05 UTC by PavlovVitalii

2022-10-15 17:08 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +).trim();
А якщо користувач натисне Esc?

2022-10-15 17:10 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +).trim();
Програма не поинна ламатися від дій користувача

2022-10-15 17:12 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +let bool = true;
я б назвав цю змінну наприклад `is Success`

2022-10-15 17:13 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +while (bool) {
тут чудова нагода використати цикл `do ... while`

2022-10-15 17:16 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +});
`arrElem` вже містить результат, можна його і вивести

2022-10-15 17:21 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +resultArray.splice(1, 2);
Треба видалити елементи з масиву з 2 по 4 (включно!), тобто три. А Ви видаляєте лише два

2022-10-15 17:28 UTC, vb-oiko requested changes
Виправте будь ласка:
- виклик методу рядка у результата промпту (якщо буде налл - отримаєте помилку)
- з масива потрібно видалити три елемента

2022-10-16 00:24 UTC, melnikovweb requested changes
Будь ласка виправте помилки які навів викладач

2022-10-16 17:38 UTC, PavlovVitalii commented on lesson_05/homework_05.1/lesson_05.1.js
> +while (bool) {
Я так і не зрозумів як тут можна використати do whole.

2022-10-17 16:59 UTC, vb-oiko commented on lesson_05/homework_05.1/lesson_05.1.js
> +while (bool) {
Ви отримуєте перший елемент від користувача до початку циклу, а інші в циклі. Я кщо використаєто конструкцію `do ... while`, всш такі операції будуть в середині циклу, а у Вашому коді буде менше повторювань

2022-10-17 18:09 UTC, vb-oiko commented on lesson_06/lesson_06.1.js
> +      array.splice(i, 1);
Ваш код працює некоректно, якщо два необхідних елемента ідуть один за одним
Наприклад
`const array = [1, 2, 3, 4, 5, 5, 6, 7, 5];`

2022-10-24 12:19 UTC, merged